apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-id
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: app-id
      securityContext: {}
      containers:
        - name: app-id
          securityContext: {}
          image: <app-id-image>
          imagePullPolicy: IfNotPresent
          env:
            # - name: REDIRECT_URL_REGEXP
            #   value: "^https:\\/\\/(.+\\.)?248\\.sh"
            - name: NEXTAUTH_URL
              value: https://id.248.sh
            # - name: NEXTAUTH_URL_INTERNAL
            #   value: http://app-id.app-id.cluster.local
            - name: GITHUB_ID
              valueFrom:
                secretKeyRef:
                  name: from-terraform
                  key: github-id
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: from-terraform
                  key: github-secret
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: from-terraform
                  key: secret
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: from-terraform-ghcr-auth
