apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-id
resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: app-id
  app.kubernetes.io/version: 0.1.7
images:
  - name: <app-id-image>
    newName: ghcr.io/248-sh/app-id
    newTag: v0.1.7
